export const OPTIONS = {
  chart: {
    type: 'pieChart',
    height: 500,
    donut: true,
    showLabels: true,
    x: (d) => d.key,
    y: (d) => d.value,
    pie: {
      dispatch: {},
      arcsRadius: [],
      width: 500,
      height: 500,
      showLabels: true,
      title: false,
      titleOffset: 0,
      labelThreshold: 0.02,
      id: 9119,
      padAngle: false,
      cornerRadius: 0,
      donutRatio: 0.5,
      labelsOutside: false,
      labelSunbeamLayout: false,
      donut: false,
      growOnHover: true,
      pieLabelsOutside: false,
      donutLabelsOutside: false,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      labelType: 'key',
      startAngle: function (d) {
        return d.startAngle / 2 - Math.PI / 2;
      },
      endAngle: function (d) {
        return d.endAngle / 2 - Math.PI / 2;
      },
    },
    duration: 500,
    legend: {
      margin: { top: 5, right: 140, bottom: 5, left: 0 },
      dispatch: {},
      width: 400,
      height: 20,
      align: true,
      maxKeyLength: 20,
      rightAlign: true,
      padding: 32,
      updateState: true,
      radioButtonMode: false,
      expanded: false,
      vers: 'classic',
    },
    dispatch: {},
    tooltip: {
      duration: 0,
      gravity: 'w',
      distance: 25,
      snapDistance: 0,
      classes: null,
      chartContainer: null,
      enabled: true,
      hideDelay: 200,
      headerEnabled: false,
      fixedTop: null,
      offset: { left: 0, top: 0 },
      hidden: true,
      data: null,
      id: 'nvtooltip-35852',
    },
    arcsRadius: [],
    width: null,
    title: false,
    titleOffset: 0,
    labelThreshold: 0.02,
    padAngle: false,
    cornerRadius: 0,
    donutRatio: 0.5,
    labelsOutside: false,
    labelSunbeamLayout: false,
    growOnHover: true,
    pieLabelsOutside: false,
    donutLabelsOutside: false,
    margin: { top: 30, right: 20, bottom: 20, left: 20 },
    labelType: 'key',
    noData: null,
    showLegend: true,
    legendPosition: 'top',
    defaultState: null,
  },
  title: { enable: false, text: 'Write Your Title', className: 'h4', css: { width: 'nullpx', textAlign: 'center' } },
  subtitle: { enable: false, text: 'Write Your Subtitle', css: { width: 'nullpx', textAlign: 'center' } },
  caption: { enable: false, text: 'Figure 1. Write Your Caption text.', css: { width: 'nullpx', textAlign: 'center' } },
  styles: { classes: { 'with-3d-shadow': true, 'with-transitions': true, gallery: false }, css: {} },
};

export const DATA: any[] = [
  {
    key: 'One',
    value: 5,
  },
  {
    key: 'Two',
    value: 2,
  },
  {
    key: 'Three',
    value: 9,
  },
  {
    key: 'Four',
    value: 7,
  },
  {
    key: 'Five',
    value: 4,
  },
  {
    key: 'Six',
    value: 3,
  },
];
