import { COLOR_PALLET } from '../../@core/datasets/color.dataset';
import { SAMPLE_CHART_SUMMARY } from '../../@core/datasets/chart-summary.dataset';

export const OPTIONS = {
  chart: {
    type: 'boxPlotChart',
    height: 450,
    margin: { top: 20, right: 20, bottom: 30, left: 50 },
    color: (_, i) => COLOR_PALLET.random[(i % COLOR_PALLET.random.length) - 1],
    maxBoxWidth: 55,
    yDomain: [0, 500],
    dispatch: {},
    boxplot: {
      dispatch: {},
      width: 960,
      height: 500,
      maxBoxWidth: null,
      id: 8674,
      y: {},
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      duration: 250,
    },
    xAxis: {
      dispatch: {},
      axisLabelDistance: 0,
      staggerLabels: true,
      rotateLabels: 0,
      rotateYLabel: true,
      showMaxMin: false,
      axisLabel: null,
      height: 60,
      ticks: null,
      width: 75,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      duration: 250,
      orient: 'bottom',
      tickValues: null,
      tickSubdivide: 0,
      tickSize: 6,
      tickPadding: 3,
      domain: [0, 1],
      range: [0, 1],
    },
    yAxis: {
      dispatch: {},
      axisLabelDistance: 0,
      staggerLabels: false,
      rotateLabels: 0,
      rotateYLabel: true,
      showMaxMin: true,
      axisLabel: null,
      height: 60,
      ticks: null,
      width: 75,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      duration: 250,
      orient: 'left',
      tickValues: null,
      tickSubdivide: 0,
      tickSize: 6,
      tickPadding: 3,
      domain: [0, 1],
      range: [0, 1],
    },
    tooltip: {
      duration: 0,
      gravity: 'w',
      distance: 25,
      snapDistance: 0,
      classes: null,
      chartContainer: null,
      enabled: true,
      hideDelay: 200,
      headerEnabled: true,
      fixedTop: null,
      offset: { left: 0, top: 0 },
      hidden: true,
      data: null,
      id: 'nvtooltip-8461',
    },
    width: null,
    y: {},
    duration: 250,
    staggerLabels: false,
    showXAxis: true,
    showYAxis: true,
    noData: 'No Data Available.',
    rightAlignYAxis: false,
  },
  ...SAMPLE_CHART_SUMMARY,
};

export const DATA: any[] = [
  {
    label: 'Sample A',
    values: {
      Q1: 180,
      Q2: 200,
      Q3: 250,
      whisker_low: 115,
      whisker_high: 400,
      outliers: [50, 100, 425],
    },
  },
  {
    label: 'Sample B',
    values: {
      Q1: 300,
      Q2: 350,
      Q3: 400,
      whisker_low: 225,
      whisker_high: 425,
      outliers: [275, 450, 480],
    },
  },
  {
    label: 'Sample C',
    values: {
      Q1: 100,
      Q2: 200,
      Q3: 300,
      whisker_low: 25,
      whisker_high: 400,
      outliers: [450, 475],
    },
  },
  {
    label: 'Sample D',
    values: {
      Q1: 75,
      Q2: 100,
      Q3: 125,
      whisker_low: 50,
      whisker_high: 300,
      outliers: [450],
    },
  },
  {
    label: 'Sample E',
    values: {
      Q1: 325,
      Q2: 400,
      Q3: 425,
      whisker_low: 225,
      whisker_high: 475,
      outliers: [50, 100, 200],
    },
  },
];
