import { COLOR_PALLET } from './../../@core/datasets/color.dataset';
import { ERR_404 } from '../../@core/datasets/ui-messages.dataset';
import { SAMPLE_CHART_SUMMARY } from '../../@core/datasets/chart-summary.dataset';

export const OPTIONS = {
  chart: {
    type: 'scatterChart',
    height: 500,
    color: (_, i) => {
      return COLOR_PALLET.random[i % 10];
    },
    scatter: {
      onlyCircles: false,
      dispatch: {},
      width: null,
      height: null,
      xDomain: null,
      yDomain: null,
      pointDomain: null,
      xRange: null,
      yRange: null,
      pointRange: null,
      forceX: [],
      forceY: [],
      forcePoint: [],
      interactive: true,
      padDataOuter: 0,
      padData: false,
      clipEdge: false,
      clipVoronoi: true,
      showVoronoi: true,
      id: 82099,
      interactiveUpdateDelay: 0,
      showLabels: true,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      duration: 500,
      useVoronoi: true,
    },
    showDistX: true,
    showDistY: true,
    duration: 350,
    xAxis: {
      axisLabel: 'X Axis',
      dispatch: {},
      axisLabelDistance: 0,
      staggerLabels: false,
      rotateLabels: 0,
      rotateYLabel: true,
      showMaxMin: true,
      height: 60,
      ticks: null,
      width: 75,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      duration: 250,
      orient: 'bottom',
      tickValues: null,
      tickSubdivide: 0,
      tickSize: 6,
      tickPadding: 10,
      domain: [0, 1],
      range: [0, 1],
    },
    yAxis: {
      axisLabel: 'Y Axis',
      axisLabelDistance: -5,
      dispatch: {},
      staggerLabels: false,
      rotateLabels: 0,
      rotateYLabel: true,
      showMaxMin: true,
      height: 60,
      ticks: null,
      width: 75,
      margin: { top: 0, right: 0, bottom: 0, left: 0 },
      duration: 250,
      orient: 'left',
      tickValues: null,
      tickSubdivide: 0,
      tickSize: 6,
      tickPadding: 10,
      domain: [0, 1],
      range: [0, 1],
    },
    zoom: {
      enabled: true,
      scaleExtent: [1, 10],
      useFixedDomain: false,
      useNiceScale: false,
      horizontalOff: false,
      verticalOff: true,
      unzoomEventType: 'dblclick.zoom',
    },
    dispatch: {},
    legend: {
      dispatch: {},
      width: 400,
      height: 20,
      align: true,
      maxKeyLength: 20,
      rightAlign: true,
      padding: 32,
      updateState: true,
      radioButtonMode: false,
      expanded: false,
      vers: 'classic',
      margin: { top: 5, right: 0, bottom: 5, left: 0 },
    },
    distX: { dispatch: {}, margin: { top: 0, right: 0, bottom: 0, left: 0 }, width: 400, size: 8, duration: 250 },
    distY: { dispatch: {}, margin: { top: 0, right: 0, bottom: 0, left: 0 }, width: 400, size: 8, duration: 250 },
    tooltip: {
      duration: 100,
      gravity: 'w',
      distance: 25,
      snapDistance: 0,
      classes: null,
      chartContainer: null,
      enabled: true,
      hideDelay: 200,
      headerEnabled: true,
      fixedTop: null,
      offset: { left: 0, top: 0 },
      hidden: true,
      data: null,
      id: 'nvtooltip-46025',
    },
    xDomain: null,
    yDomain: null,
    pointDomain: null,
    xRange: null,
    yRange: null,
    pointRange: null,
    forceX: [],
    forceY: [],
    forcePoint: [],
    interactive: true,
    padDataOuter: 0.1,
    padData: false,
    clipEdge: false,
    clipVoronoi: true,
    showVoronoi: false,
    interactiveUpdateDelay: 0,
    showLabels: false,
    margin: { top: 40, right: 40, bottom: 50, left: 70 },
    useVoronoi: true,
    container: null,
    showLegend: true,
    showXAxis: true,
    showYAxis: true,
    defaultState: null,
    noData: ERR_404,
    rightAlignYAxis: false,
    // pointActive: (d) => d.shape !== 'triangle-up',
  },
  ...SAMPLE_CHART_SUMMARY,
};

export const DATA = generateData(7, 10);

function generateData(groups: number, points: number) {
  let data = [];
  let shapes = ['circle', 'circle', 'triangle-up', 'triangle-down', 'diamond', 'square'];

  for (let i = 0; i < groups; i++) {
    data.push({ key: 'Group ' + (i + 1), values: [] });

    for (let j = 0; j < points; j++) {
      data[i].values.push({
        x: Math.floor(Math.random() * 100),
        y: Math.floor(Math.random() * 100),
        size: Math.random(),
        shape: shapes[j % 6],
      });
    }
  }
  return data;
}
